[package]
name = "pie_coin"
version = "0.1.0"
authors = ["Toby Hughes <tobywhughes@gmail.com>"]

[dependencies]
time = "*"
rand = "*"
rust-crypto = "*"
serde = "1.0"
serde_derive = "1.0"
bincode = "0.9.2"
